dependencies :
  - file
  - media
  - image
variables :
  file_extensions :
    type : string
    placeholder : 'png gif jpg jpeg'
    required : false
    default : 'png gif jpg jpeg'
    description: Provide list of extensions seperated by space. Eg. 'png gif jpg jpeg'
